### ISSUE TITLE
Draw a polygon and show with MapView

### ISSUE THREAD

**Issue by brunopacola** [OsmSharp/ui#122]
Hi, 

I have a MBTiles file and I'm showing with MapView. I need to draw a polygon and show up on this MBTiles file. How do I do that?

Illustrative example:

![example](https://cloud.githubusercontent.com/assets/1854886/3148045/4caa1e14-ea5c-11e3-9aa0-936534cb6351.gif)

**Comment by Workerbee** [comment]
Is there example code of how this works? I've added a polygon to the map but it doesnt show.

**Comment by xivk** [comment]
Can you try to use another value for 'color'. You can use the SimpleColor struct to do this. Some examples here:

https://github.com/OsmSharp/ui/blob/master/OsmSharp.UI.Test/SimpleColorTests.cs#L65

You can use (SimpleColor).Value to get the argb integer.

**Comment by Workerbee** [comment]
Thanks that fixed it :+1:
