### ISSUE TITLE
Route instructions are sometimes incomplete

### ISSUE THREAD

**Issue by JoeCooper** [OsmSharp/ui#229]
I'm including an image. For the route shown on the left – which resolves and renders correctly – I get near-empty instructions. (Only the starting and ending POI are in the instruction series.)

If you still have my files, you can reproduce it with the following coordinates:

From: 47.1480665604869, -102.461533504644
To: 47.18302107, -102.49835487

![route-interpretation](https://cloud.githubusercontent.com/assets/5166338/7229212/5f1b1b18-e761-11e4-818d-549f207d07f0.png)

I dug in a bit and found the misbehavior seems to happen somewhere in MicroPlanner; the route seems to be perfectly valid and AggregatedPoint that goes in seems to be valid (so far as I can tell) but none of the "machines" seem to come up with anything except for PoiMachine and PoiWithTurnMachine.

The second instruction has the next "poi" and nothing else, which (as shown in the screenshot here) is processed a bit.

**Comment by xivk** [comment]
Thanks, this is definetly a bug. There should at least be one instruction that says something like 'Turn left onto {streetname}'. 

Am I also correct in assuming that you are also missing instructions like 'Start heading west/north/east/south on {streetname}'. Something that is not common in Europe but is used in the US?

**Comment by JoeCooper** [comment]
It's completely empty except for the two "poi" instructions.

Many routes _do_ appear correctly, with turns listed and all that, but this one does not.

**Comment by JoeCooper** [comment]
Hey how's this coming?

**Comment by JoeCooper** [comment]
I can't reproduce this anymore. If I do find such a problem again and trace it to OsmSharp than I'll send a pull request instead of a bug report.
