### ISSUE TITLE
Endpoint resolution a little off

### ISSUE THREAD

**Issue by JoeCooper** [OsmSharp/ui#244]
Client sent the following screenshot. I've confirmed that the problem isn't a gap in the image. Any hints about why this might be like this?

![20150611_114424](https://cloud.githubusercontent.com/assets/5166338/8129163/8a4dbaf6-1106-11e5-921d-fe2b1cb33810.jpg)

**Comment by xivk** [comment]
No not really an idea at the moment, except maybe that this point may be at the edge of the loaded network?

Any way to reproduce this?

**Comment by JoeCooper** [comment]
Can't reproduce this. Could have been a data problem. If I find something like it again I'll solve it and submit a pull request. No worries.
