### ISSUE TITLE
[Meta] GitHub Wiki Still Has Information About Routing

### ISSUE THREAD

**Issue by airbreather** [OsmSharp/ui#285]
Looks like the routing component was spun out into Itinero, but the OsmSharp wiki didn't get the memo.

Some sample pages that still think routing is part of OsmSharp (not sure if this is all of them on this project's wiki, and I didn't bother looking at other OsmSharp projects):

- [The Main One](https://github.com/OsmSharp/ui/wiki)
- [A getting started example](https://github.com/OsmSharp/ui/wiki/A-getting-started-example)
- [Loading a routing graph](https://github.com/OsmSharp/ui/wiki/Loading-a-routing-graph)
- [Serializing a routing graph](https://github.com/OsmSharp/ui/wiki/Serializing-a-routing-graph)

**Comment by airbreather** [comment]
Never mind, you've made it clear that this isn't maintained anymore.  Heh.

**Comment by xivk** [comment]
I removed the wiki, it's configusing! 👍
